name: Publish to GitHub Packages

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ outbox-prod.PAT_TOKEN }}

      - name: Build and publish
        run: ./gradlew clean build publish
        env:
          USERNAME: ${{ outbox-prod.USERNAME }}
          PAT_TOKEN: ${{ outbox-prod.PAT_TOKEN }}
